version: "3.8"
services:
  ma-connector:
    build: .
    image: ma-connector
    devices:
      - "/dev/piControl0:/dev/piControl0"
    volumes:
      - ./config:/app/config:ro
      - ./data:/app/data:ro
    environment:
      JAVA_TOOL_OPTIONS: "-DLOG_LEVEL=INFO"
