core:
  baseUrl: "http://localhost:8080/"
keycloak:
  tokenUrl: "http://localhost:8082/realms/pegelhub/protocol/openid-connect/token"
  clientId: "connector"
  clientSecret: "secret"
schedule:
  delay: "30s"
mappingsDir: "mappings"
