core:
  baseUrl: "http://live-suite:18080/"
keycloak:
  tokenUrl: "http://live-suite:18082/realms/pegelhub/protocol/openid-connect/token"
  clientId: "iec"
  clientSecret: "secret"
schedule:
  delay: "1s"
mappingsDir: "mappings"
iec:
  address: "live-suite"
  port: 2404
  commonAddress: 1
